### ISSUE TITLE
livecd-creation failure on chapeau22

### ISSUE THREAD

**Issue by JazzMaster** [chapeaulinux/build-kit#3]
./livecd-creator.sh --cache=/home/me/ks/cache --config=/home/me/ks/chapeau-22.ks --verbose
SELinux status:                 enabled
Current mode:                   permissive

broadcom-wl-5.100.138.tar.bz2 downloaded successfully
Download of <<<<<<< HEAD failed from URL <<<<<<< HEAD. Aborting.
mediaplayer%40patapon.info.v33.shell-extension.zip downloaded successfully
caffeine%40patapon.info.v21.shell-extension.zip downloaded successfully
Download of ======= failed from URL =======. Aborting.
mediaplayer@patapon.info.shell-extension.zip?version_tag=4791 downloaded successfully
caffeine%40patapon.info.shell-extension.zip?version_tag=4792 downloaded successfully
Download of >>>>>>> 22 failed from URL >>>>>>> 22. Aborting.
rpmfusion-free-release-22.noarch.rpm downloaded successfully
rpmfusion-nonfree-release-22.noarch.rpm downloaded successfully
./livecd-creator.sh: line 121: syntax error near unexpected token `<<<'
./livecd-creator.sh: line 121:`<<<<<<< HEAD'

Last error repeats itself when relaunching the script, even though cache is removed.Files in /var/tmp remain and so does the mount for those files, forcing a reboot to clear the cache in /var/tmp. Using these 'release' files for RPMFusion(already installed) causes a key management bug to occur, as noted on the facebook site that chapeau team refuses to acknowledge or act upon.These files from RPMFusion conflict with chapeau installed keys for fc22 causing the internal package of livecd-creator to fail to build the ISO. It would appear that we are recreating this bug again with the github version of build-kit.

**Comment by vpooley** [comment]
I can see the issue causing that syntax error, you have not downloaded version 22 of the build-kit, you've downloaded from either the master branch or the 23 branch, both are in mid-merge with a couple of merge conflicts at the moment and are thus temporarily broken until I complete the merge.
Download the build-kit for 21 or 22 archive from the appropriate branch or clone the repo with git and checkout the preferred branch.
21 branch = https://github.com/chapeaulinux/build-kit/archive/21.zip
22 branch = https://github.com/chapeaulinux/build-kit/archive/22.zip

Why are you running the livecd-creator.sh script with arguments? It doesn't expect or use any and the instructions don't tell you to. Please follow the build-kit instructions in [the included readme](https://github.com/chapeaulinux/build-kit/blob/22/README.md).

The rpmfusion-release rpms from rpmfusion.org aren't used in Chapeau 22, they're downloaded for my reference only by the build script but they are not installed in Chapeau. The rpmfusion repo files and gpg keys are maintained by me and are in the chapeau-repos package as you can see in the 22 branch of [the chapeau-repos Git repo](https://github.com/chapeaulinux/chapeau-repos/tree/22).
If your kickstart is trying to install those rpmfusion packages then that is your amendment and therefore it is not a bug with Chapeau or the build-kit, the build-kit works just fine.

No-one's refusing to acknowledge bugs but there needs to be a bug to start with and some sort of evidence. Your thread about packages was closed on the support forum because it was clear there was no real issue, no evidence was provided and the thread was going nowhere.
